name: "Setup Python and Poetry"

description: "Sets up Python, installs Poetry, caches dependency environments, and installs dependencies."

inputs:
  python_version:
    description: "Python version to use."
    required: false
    default: "3.13"

outputs:
  python_version:
    description: "The Python version that was installed."
    value: ${{ steps.setup-python.outputs.python-version }}

runs:
  using: "composite"
  steps:
    - name: Set up Python
      id: setup-python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}
        cache: "poetry"

    - name: Install Poetry and dependencies
      shell: bash
      run: |
        # (Optional) Upgrade pip
        python -m pip install --upgrade pip

        # Install Poetry via pip
        pip install poetry

        # Now, we can call `poetry` in the same script
        poetry install --no-ansi --no-interaction

    - name: Set outputs
      id: set-outputs
      shell: bash
      run: |
        echo "python_version=${{ steps.setup-python.outputs.python-version }}" >> $GITHUB_OUTPUT
