name: "Setup Python and Poetry"
description: "Sets up Python, installs Poetry, caches dependency environments, and installs dependencies."

inputs:
  python_version:
    description: "Python version to use."
    required: false
    default: "3.13"

outputs:
  python_version:
    description: "The Python version that was installed."
    value: ${{ steps.setup-python.outputs.python-version }}

runs:
  using: "composite"
  steps:

    - name: Set up Python
      id: setup-python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}
        cache: "poetry"

    - name: Cache Poetry installation
      uses: actions/cache@v4
      with:
        path: ~/.local
        key: poetry-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Install dependencies
      shell: bash
      run: poetry install --no-interaction --no-ansi

    - name: Set outputs
      id: set-outputs
      shell: bash
      run: |
        echo "python_version=${{ steps.setup-python.outputs.python-version }}" >> $GITHUB_OUTPUT
