name: CI

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  commit-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python and Poetry
        id: setup-poetry
        uses: ./.github/actions/setup-poetry
        with:
          python_version: "3.13"

      - name: Conventional Commits Check
        env:
          REV_RANGE: "origin/${{ github.base_ref }}..HEAD"
        run: |
          echo "Checking commits with range: $REV_RANGE"
          poetry run cz check --rev-range "$REV_RANGE"

  lint-and-test:
    needs: [commit-check]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.13"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Python and Poetry
        id: setup-poetry
        uses: ./.github/actions/setup-poetry
        with:
          python_version: ${{ matrix.python-version }}

      - name: Run tests
        run: |
          poetry run pytest --maxfail=1 --disable-warnings -v
